name: Deploy Backend to Hugging Face

on:
  push:
    branches:
      - main
    paths:
      - "Back-end/**"
      - ".github/workflows/deploy-backend-to-hf.yml"

  workflow_dispatch:

jobs:
  sync-backend-to-huggingface:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Sync Backend folder to Hugging Face Space
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: nafta886/kopi-capstone-backend
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: docker
          subdirectory: Back-end
